---
#- name: debug key
#  debug:
#    msg: "variables {{rhsm_key_id}} and {{rhsm_org_id}}"

- name: Force unregister before register
  redhat_subscription:
    state: absent
  ignore_errors: true
  become: true

- name: Customer portal registration
  redhat_subscription:
    state: present
    username: "{{rhsm_username}}"
    password: "{{rhsm_password}}"
    autosubscribe: false
  register: result
  until: result | succeeded
  retries: 10
  delay: 5      
  become: true
  when: (rhsm_username is defined) and
        (rhsm_password is defined)  

#- name: Activation key registration
#  redhat_subscription:
#    state: "present"
#    activationkey: "{{ rhsm_key_id }}"
#    org_id: "{{ rhsm_org_id }}"
#    autosubscribe: false
#  register: result
#  until: result | succeeded
#  retries: 10
#  delay: 5
#  become: true
#  when: (rhsm_key_id is defined) and
#        (rhsm_org_id is defined)

- name: Subscribe to pool
  shell: /usr/bin/subscription-manager attach --pool={{ rhsm_pool }}
  register: task_result
  until: task_result.rc == 0
  retries: 10
  delay: 5
  ignore_errors: no      
  become: true
  when: rhsm_pool is defined

- name: Disable Repos
  shell: 'subscription-manager repos --disable="*"'
  register: result
  until: result | succeeded
  retries: 10
  delay: 5      
  become: true

- name: Enable required repos
  shell: 'subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-server-ose-{{ocp_version}}-rpms" --enable="rhel-7-fast-datapath-rpms --enable="rhel-7-server-jb-eap-7.0-containers" --enable="cf-me-5.9-for-rhel-7-containers" --enable="rhel-7-server-rhamp-1.0-containers" --enable="rhel-7-server-3scale-amp-2.1-containers" --enable="rhel-7-server-jboss-mm-7.0-techpreview-containers"'
  register: result
  until: result | succeeded
  retries: 10
  delay: 5      
  become: true
